/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.maiorsi.elasticsearch;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;

class LibraryTest {
    @Test void findDataAfterMagicBytes() {
        byte[] inBytes = { 1, 2, 58, 48, 0, 1 };

        byte[] outBytes = RoaringBitmapFilterPlugin.findDataWithMagicBytes(inBytes);

        assertArrayEquals(new byte[]{ 58, 48, 0, 1 }, outBytes);

        inBytes = new byte[]{1, 2, 3, 4, 58, 48, 0, 1 };

        outBytes = RoaringBitmapFilterPlugin.findDataWithMagicBytes(inBytes);

        assertArrayEquals(new byte[] { 58, 48, 0, 1 }, outBytes);

        inBytes = new byte[] { 1, 2, 3, 4, 59, 48, 0, 1 };

        outBytes = RoaringBitmapFilterPlugin.findDataWithMagicBytes(inBytes);

        assertArrayEquals(new byte[] { 59, 48, 0, 1 }, outBytes);
    }
}
