/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.1.0/userguide/building_java_projects.html in the Gradle documentation.
 */

group = "io.github.maiorsi.elasticsearch"
version = "0.1.0"

plugins {
    // Apply the java-library plugin for API and implementation separation.
    id("base")
    id("java-library")
}

repositories {
    mavenCentral()
}

dependencies {
    api("org.roaringbitmap:RoaringBitmap:1.3.0")
    compileOnly("org.elasticsearch:elasticsearch:9.1.1")
    testImplementation("org.elasticsearch:elasticsearch:9.1.1")
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

tasks.register(name = "distZip", type = Zip::class) {
     dependsOn(tasks.named("build"))
     from(layout.buildDirectory.dir("libs")) {
         include("*.jar")
     }
     from(configurations.runtimeClasspath)
     from(layout.projectDirectory.dir("src/assembly")) {
         include("plugin-descriptor.properties")
     }
     archiveFileName.set("es-rb-plugin.zip")
     destinationDirectory.set(file(layout.buildDirectory.dir("distributions")))
 }
